// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Armstrong__ArmstrongController from "./armstrong/armstrong_controller"
application.register("armstrong--armstrong", Armstrong__ArmstrongController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
