version: '2'

services:
  db:
    image: postgres:10.3-alpine
  ci:
    build: .
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails javascript:install:esbuild && bundle exec rails css:install:bootstrap && bundle exec rails db:create db:migrate && bundle exec rake test"
